###
POST http://127.0.0.1:5001/sae-supersaas-manager/us-central1/getStudentDataWebHook HTTP/1.1
content-type: application/json

{
    "api_key": "pE4XV7mkJXqfHqzaf7FJ6yp53dsBROyQRg3FPLYjB7BnSUWDAvFQU9jKFdALl8gf",
    "name": "Squat",
    "reps": 10,
    "weight": 30,
    "unit": "lbs",
    "date": "08-10-21"
}